version: "3"

services:
  escalator-api:
    build: ./api
    command: npm start
    ports:
      - "5001:5001"
    volumes:
      - .:/usr/app
  escalator-client:
    build: ./client
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app